### ISSUE TITLE
Not updating to latest server version

### ISSUE THREAD

**Issue by ChrisScrace** [datael/docker-dedicated-server-necesse#2]
Changing SERVER_DOWNLOAD_URL in .env following does not update the server:
`https://necessegame.com/wp-content/uploads/2023/08/necesse-server-linux64-0-22-1-12080883.zip`

The logs on server start still show:
`Loading dedicated server on version 0.21.23.`

**Comment by datael** [comment]
Sorry to have taken so long to reply.

How are you building the docker image? Are you getting any errors?

The only times I can think of that you'd still see an old log is if:
- There was an error when building the docker image and an old one is being used
    - docker compose _should_ fail when this happens, though
- The people who make the game forgot to update the version in the logs
    - This doesn't appear to be the case; I was able to launch with the URL you posted

**Comment by ChrisScrace** [comment]
I did get it working in the end, sorry should have come back and updated here. If memory serves I had to remove the original server manually and then run it again, changing the url alone didn't update it automatically.

**Comment by datael** [comment]
Thanks for getting back to me!
Will close this out in that case.

Glad you got it working in the end.
